name: Artifacts

on:
  push:
    branches:
      - master
      - release/*
      - ci/*
  pull_request:
    branches:
      - master
      - release/*
      - ci/*

jobs:

  publish-gcp:
    name: Згидшыр ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest", "macos-latest", "ubuntu-latest", "macos-13" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_ARTIFACTS_KEY }}
          export_default_credentials: true

        # needed for GitVersion
      - name: Fetch all history
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

        # step id used as reference for output values
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 0
          format: 'YYYYMMDD-HHmm'

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: distZip

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Set filename
        id: set-filename
        run: echo "targetFile=dshackle-archive" >> "$GITHUB_OUTPUT"
        if: runner.os != 'Windows'

      - name: Set filename
        id: set-filename
        run: echo "targetFile=dshackle-archive.exe" >> "$GITHUB_OUTPUT"
        if: runner.os == 'Windows'

      - name: Upload to GCP
        run: |
          gsutil cp -n ${{ steps.set-filename.outputs.targetFile }} gs://artifacts.emerald.cash/builds/dshackle-archive/${{ steps.gitversion.outputs.commitDate }}/${{ steps.time.outputs.time }}-${{ steps.gitversion.outputs.shortSha }}/

      - name: Links to published artifacts
        run: |
          echo "Publishing artifacts to:"
          echo "  https://artifacts.emerald.cash/builds/dshackle-archive/${{ steps.gitversion.outputs.commitDate }}/${{ steps.time.outputs.time }}-${{ steps.gitversion.outputs.shortSha }}/${{ steps.set-filename.outputs.targetFile }}"

      - name: Attach artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          overwrite: true
          path: |
            target/release/dshackle-archive
            target/release/dshackle-archive.exe
